version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: /
    schedule:
      interval: monthly
    labels:
      - 'no-changelog'

  - package-ecosystem: 'npm'
    directory: /
    schedule:
      interval: monthly
    groups:
      npm-dependencies:
        patterns:
          - '*'
    labels:
      - 'no-changelog'
    ignore:
      - dependency-name: '@types/vscode'
      - dependency-name: '@types/node'
      - dependency-name: 'vscode-languageclient'
